"""
Model Comparison Component — Compare all 6 models side by side.
Loads real per-model metrics from model_comparison_metrics.csv
(generated by evaluate.py) instead of using scaled approximations.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import json

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import DATA_DIR

# One color per model so charts stay visually consistent across the dashboard
MODEL_COLORS = {
    "Isolation Forest": "#3B82F6",
    "One-Class SVM": "#6B7280",
    "LSTM Autoencoder": "#00FF88",
    "Transformer": "#14B8A6",
    "XGBoost": "#F59E0B",
    "Random Forest": "#8B5CF6",
}

MODEL_DESCRIPTIONS = {
    "Isolation Forest": "Unsupervised — isolates outliers via random partitioning of feature space",
    "One-Class SVM": "Unsupervised — learns a tight boundary around normal behaviour",
    "LSTM Autoencoder": "Sequence-aware — reconstructs temporal event patterns, flags high error",
    "Transformer": "Self-attention — captures non-local temporal dependencies in event sequences",
    "XGBoost": "Supervised — gradient-boosted trees for multi-class attack classification",
    "Random Forest": "Supervised — bagged decision trees, compared against XGBoost",
}


def render_model_comparison(alert_df):
    """Render model comparison panel with real metrics."""
    st.subheader("🔬 Model Comparison")

    # Load real per-model metrics generated by evaluate.py
    comp_path = DATA_DIR / "model_comparison_metrics.csv"
    if not comp_path.exists():
        st.warning(
            "Model comparison metrics not found. Run the evaluation pipeline first:\n\n"
            "```\npython evaluate.py\n```"
        )
        return

    comp_df = pd.read_csv(comp_path, index_col=0)

    # Let the user pick which models to compare
    available_models = list(comp_df.index)
    selected = st.multiselect(
        "Compare Models",
        available_models,
        default=available_models,
    )

    if not selected:
        st.info("Select at least one model to compare.")
        return

    filtered = comp_df.loc[selected]

    # ── Metrics table ────────────────────────────────────────────────────
    st.markdown("#### Performance Metrics")
    display_df = filtered.round(4).copy()
    display_df.index.name = "Model"
    st.dataframe(display_df, use_container_width=True)

    # ── Bar chart comparison ─────────────────────────────────────────────
    st.markdown("#### Metric Comparison")
    metric_cols = [c for c in filtered.columns if c in ["Precision", "Recall", "F1-Score", "Accuracy"]]

    fig = go.Figure()
    for model in selected:
        color = MODEL_COLORS.get(model, "#999999")
        fig.add_trace(go.Bar(
            name=model,
            x=metric_cols,
            y=[filtered.loc[model, c] for c in metric_cols],
            marker_color=color,
        ))

    fig.update_layout(
        barmode="group",
        yaxis_title="Score", yaxis_tickformat=".0%",
        height=420, margin=dict(l=20, r=20, t=40, b=20),
    )
    st.plotly_chart(fig, use_container_width=True)

    # ── Radar chart ──────────────────────────────────────────────────────
    st.markdown("#### Performance Radar")
    categories = metric_cols + [metric_cols[0]]

    fig = go.Figure()
    for model in selected:
        color = MODEL_COLORS.get(model, "#999999")
        values = [filtered.loc[model, c] for c in metric_cols]
        values.append(values[0])

        r, g, b = int(color[1:3], 16), int(color[3:5], 16), int(color[5:7], 16)
        fig.add_trace(go.Scatterpolar(
            r=values, theta=categories,
            fill="toself",
            fillcolor=f"rgba({r},{g},{b},0.12)",
            line=dict(color=color, width=2),
            name=model,
        ))

    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
        title="Model Performance Radar",
        height=450, margin=dict(l=60, r=60, t=60, b=60),
    )
    st.plotly_chart(fig, use_container_width=True)

    # ── Model descriptions ───────────────────────────────────────────────
    st.markdown("#### Model Details")
    for model in selected:
        desc = MODEL_DESCRIPTIONS.get(model, "")
        color = MODEL_COLORS.get(model, "#999999")
        st.markdown(f"**{model}:** {desc}")

    # ── Design Decisions ─────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("#### Design Decisions")

    # LSTM vs Transformer
    if "LSTM Autoencoder" in comp_df.index and "Transformer" in comp_df.index:
        lstm_row = comp_df.loc["LSTM Autoencoder"]
        tf_row = comp_df.loc["Transformer"]
        lstm_prec = lstm_row.get("Precision", 0)
        tf_prec = tf_row.get("Precision", 0)
        lstm_f1 = lstm_row.get("F1-Score", 0)
        tf_f1 = tf_row.get("F1-Score", 0)

        with st.expander("Why LSTM over Transformer for the risk score formula?", expanded=True):
            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**LSTM Autoencoder**")
                st.metric("Precision", f"{lstm_prec:.4f}")
                st.metric("F1-Score", f"{lstm_f1:.4f}")
            with col2:
                st.markdown("**Transformer**")
                st.metric("Precision", f"{tf_prec:.4f}")
                st.metric("F1-Score", f"{tf_f1:.4f}")

            st.markdown(f"""
**LSTM wins on precision ({lstm_prec:.3f} vs {tf_prec:.3f})** — the metric that matters most
for a risk-scoring component feeding a SOC alert queue. A high-precision anomaly signal
means fewer false positives, so analysts trust the alerts they see.

The Transformer's self-attention captures non-local temporal patterns but produces
more false positives on this dataset, lowering precision. Both models are trained and
available; the risk score formula uses LSTM (weight 0.35) while the Transformer remains
deployed for comparison and future experimentation.

**Risk Score Formula:**
`0.35 × IF + 0.35 × LSTM + 0.20 × classifier_confidence + 0.10 × entity_history`
""")

    # XGBoost vs Random Forest
    if "XGBoost" in comp_df.index and "Random Forest" in comp_df.index:
        xgb_row = comp_df.loc["XGBoost"]
        rf_row = comp_df.loc["Random Forest"]
        xgb_f1 = xgb_row.get("F1-Score", 0)
        rf_f1 = rf_row.get("F1-Score", 0)
        xgb_prec = xgb_row.get("Precision", 0)
        rf_prec = rf_row.get("Precision", 0)

        with st.expander("Why XGBoost over Random Forest for classification?", expanded=True):
            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**XGBoost**")
                st.metric("F1-Score", f"{xgb_f1:.4f}")
                st.metric("Precision", f"{xgb_prec:.4f}")
            with col2:
                st.markdown("**Random Forest**")
                st.metric("F1-Score", f"{rf_f1:.4f}")
                st.metric("Precision", f"{rf_prec:.4f}")

            st.markdown(f"""
**XGBoost dominates with F1 {xgb_f1:.4f} vs RF {rf_f1:.4f}.** Gradient boosting learns
from previous trees' residuals, giving it an edge on imbalanced multi-class classification.
Random Forest's bagging approach treats all trees independently, which limits its ability
to correct misclassifications on rare attack types like credential stuffing and low-and-slow.
""")
